[package]
name = "boytacean-libretro"
version = "0.9.14"
authors = ["João Magalhães <joamag@gmail.com>"]
description = "A Lib Retro frontend for Boytacen"
license = "Apache-2.0"
keywords = ["gameboy", "emulator", "rust", "libretro"]
edition = "2018"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[features]
debug = ["boytacean/debug"]
pedantic = ["boytacean/pedantic"]
cpulog = ["boytacean/cpulog"]

[dependencies.boytacean]
path = "../.."

[target.aarch64-linux-android]
ar = "./ndk/arm64/bin/aarch64-linux-android-ar"
linker = "./ndk/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "./ndk/arm/bin/arm-linux-androideabi-ar"
linker = "./ndk/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "./ndk/x86/bin/i686-linux-android-ar"
linker = "./ndk/x86/bin/i686-linux-android-clang"
